logging:
  receivers:
    my-app-receiver:
      type: files
      include_paths:
        - /tmp/application.log
      record_log_file_path: true
  processors:
    webapp-processor:
      type: parse_json
      time_key: time
      time_format: "%Y-%m-%dT%H:%M:%S.%L%Z"
    set_severity:
      type: modify_fields
      fields:
        severity:
          move_from: jsonPayload.severity
  service:
    pipelines:
      pipeline:
        receivers: [my-app-receiver]
        processors: [webapp-processor, set_severity]