name: Packer Build

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Packer Build
    runs-on: ubuntu-latest

    if: github.event.pull_request.merged == true

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'temurin'
          cache: maven

      - name: Setup MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql database: 'db'
          mysql user: 'test'
          mysql password: 'intTest@123'

      - name: gcloud action runner
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Test
        run: |
          pwd
          ls -al
          mvn clean install -DskipTests=true        

      - name: Initialize and Validate Packer Template
        run: |
          packer init ./packer/base-centos.pkr.hcl
          packer validate ./packer/base-centos.pkr.hcl

      - name: Format Packer Template
        run: |
          packer fmt ./packer/base-centos.pkr.hcl

      - name: Build Image with Packer
        run: |
          packer build ./packer/base-centos.pkr.hcl

      - name: fetching image name
        run: |
          gcloud config set project ${{ secrets.PROJECT }}
          latest_image_id=$(gcloud compute images list  --sort-by=creationTimestamp --format='value(id)' --limit=1)
          echo "$latest_image_id"
          

      - name: Create new Template
        run: |
          gcloud beta compute instance-templates create ${{ secrets.TEMPLATE_NAME }}
          --project= ${{ secrets.PROJECT }}
          --machine-type= ${{ secrets.MACHINE }}
          --network-interface=network-tier=STANDARD,subnet= ${{ secrets.SUBNET }}
          --instance-template-region= us-east4
          --metadata=startup-script= ${{ secrets.SCRIPT }}
          --maintenance-policy=MIGRATE
          --region=us-east4
          --provisioning-model=STANDARD
          --service-account= ${{ secrets.SERVICE_ACCOUNT }}
          --scopes= ${{ secrets.SCOPE }}
          --tags=webapp-instance
          --create-disk=auto-delete=yes,boot=yes,device-name=persistent-disk-0,image=projects/dev-demo-415618/global/images/$latest_image_id,kms-key=projects/dev-demo-415618/locations/us-east4/keyRings/terraform-managed-key5/cryptoKeys/vm-encryption-key,mode=rw,size=20,type=pd-standard
          --no-shielded-secure-boot --shielded-vtpm --shielded-integrity-monitoring
          --reservation-affinity=any

      - name: Set new Template for the group
        run: |
          gcloud compute instance-groups managed set-instance-template \
          webapp-instance-group3 --template=${{ secrets.TEMPLATE_NAME }}
          

      - name: Create new Template
        run: |
          gcloud compute instance-groups managed rolling-action start-update \
          webapp-instance-group3 \
          --version=template=${{ secrets.TEMPLATE_NAME }} \
          --max-surge=5
