name: Packer Validation

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Integration Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Setup MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          mysql database: 'db'
          mysql user: 'test'
          mysql password: 'intTest@123'

      - name: Test
        run: |
          pwd
          ls -al
          mvn clean install -DskipTests=true

      - name: Setup Packer
        uses: hashicorp/setup-packer@main

      - name: Initialize Packer template
        id: init
        run: "packer init ./packer/base-centos.pkr.hcl"

      - name: Initialize Packer template
        id: fmt
        run: "packer fmt -check ./packer/base-centos.pkr.hcl"

      - name: Validate Packer template
        id: validate
        run: "packer validate ./packer/base-centos.pkr.hcl"
