on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup MySQL
        uses: mirromutth/mysql-action@v1.1
        with:
          'mysql database': csye6225
          'mysql user': root
          'mysql password': 12345678
          'host port': 3306
          'container port': 3306
          'character set server': utf8mb4
          'collation server': utf8mb4_general_ci
          'mysql version': latest
          'mysql root password': '${{ secrets.MYSQL_ROOT_PASSWORD }}'

      - name: Install Maven
        run: |
          sudo apt-get update
          sudo apt-get install -y maven

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: Start MySQL Service
        run: |
          sudo service mysql start

      - name: Database Setup
        run: |
          # You can perform additional database setup tasks here if needed

      - name: Run Maven Clean Install
        run: |
          mvn clean install

      - name: Running Integration Tests
        run: |
           mvn test
